from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any


def _bar(value: float, color: str) -> str:
    width = max(0.0, min(100.0, value * 100))
    return f'<span class="bar"><i style="width:{width:.1f}%;background:{color}"></i></span> {value:.3f}'


def write_html(report: dict[str, Any], path: str | Path) -> None:
    rows = []
    for task in report["tasks"]:
        depth = "stable" if task["first_unstable_depth"] is None else str(task["first_unstable_depth"])
        rows.append(
            "<tr>"
            f"<td><strong>{html.escape(task['task_id'])}</strong><small>{task['successes']}/{task['runs']} passed</small></td>"
            f"<td>{_bar(task['success_rate'], '#61d095')}</td>"
            f"<td>{_bar(task['composition_consistency'], '#75a7ff')}</td>"
            f"<td>{_bar(task['order_consistency'], '#ffb86b')}</td>"
            f"<td>{depth}</td><td>{task['peak_entropy_bits']:.3f}</td>"
            "</tr>"
        )
    data = html.escape(json.dumps(report, indent=2))
    summary = report["summary"]
    document = f"""<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>Branchpoint report</title>
<style>
:root {{ color-scheme: dark; font-family: ui-monospace, SFMono-Regular, monospace; background:#0d1117; color:#e6edf3 }}
body {{ max-width:1000px; margin:4rem auto; padding:0 1rem }} h1 {{ font-size:clamp(2rem,7vw,5rem); margin:0 }}
.lede {{ color:#9da7b3; max-width:70ch }} .cards {{ display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:1rem;margin:2rem 0 }}
.card,table,details {{ background:#161b22;border:1px solid #30363d;border-radius:12px }} .card {{ padding:1rem }} .card b {{ display:block;font-size:2rem }}
table {{ border-collapse:separate;border-spacing:0;width:100%;overflow:hidden }} th,td {{ padding:.8rem;text-align:left;border-bottom:1px solid #30363d }} tr:last-child td {{ border:0 }}
small {{ display:block;color:#8b949e;margin-top:.25rem }} .bar {{ display:inline-block;width:6rem;height:.55rem;background:#30363d;border-radius:1rem;overflow:hidden }} .bar i {{ display:block;height:100% }}
details {{ margin-top:1rem;padding:1rem }} pre {{ overflow:auto;color:#b8c4d0 }} a {{color:#75a7ff}} @media(max-width:700px){{th:nth-child(3),td:nth-child(3){{display:none}}}}
</style>
<body><p>AI AGENT RELIABILITY / OFFLINE REPORT</p><h1>Where did the runs branch?</h1>
<p class="lede">Branchpoint keeps outcome success separate from tool-composition and ordering consistency. The unstable depth is the first action position whose Shannon entropy is non-zero.</p>
<section class="cards"><div class="card"><b>{summary['task_count']}</b> tasks</div><div class="card"><b>{summary['run_count']}</b> runs</div><div class="card"><b>{summary['mean_success_rate']:.3f}</b> mean success</div><div class="card"><b>{summary['mean_order_consistency']:.3f}</b> order consistency</div></section>
<table><thead><tr><th>Task</th><th>Success</th><th>Composition</th><th>Order</th><th>First unstable depth</th><th>Peak entropy</th></tr></thead><tbody>{''.join(rows)}</tbody></table>
<details><summary>Machine-readable report</summary><pre>{data}</pre></details>
<p class="lede">Generated by <a href="https://github.com/ikorfale/bemjamin-lab">Branchpoint</a>. No model or network call was used.</p></body></html>"""
    Path(path).write_text(document, encoding="utf-8")

